import {
  Account,
  Category,
  CategorySpend,
  MerchantSpend,
  MonthlySummary,
  Transaction,
} from "./api";

export const DUMMY_ACCOUNTS: Account[] = [
  { id: "acc-1", name: "Chase Sapphire Checking", account_type: "CHECKING", currency: "USD" },
  { id: "acc-2", name: "Amex Platinum Card", account_type: "CREDIT", currency: "USD" },
  { id: "acc-3", name: "Apple Card", account_type: "CREDIT", currency: "USD" },
  { id: "acc-4", name: "Vanguard Total Market Index", account_type: "INVESTMENT", currency: "USD" },
];

export const DUMMY_CATEGORIES: Category[] = [
  { id: 1, name: "Housing & Rent" },
  { id: 2, name: "Groceries & Food" },
  { id: 3, name: "Dining & Coffee" },
  { id: 4, name: "Travel & Transport" },
  { id: 5, name: "Software & SaaS" },
  { id: 6, name: "Health & Fitness" },
  { id: 7, name: "Income & Payroll" },
];

export const DUMMY_BY_CATEGORY: CategorySpend[] = [
  { category: "Housing & Rent", total_spent: "2400.00", transaction_count: 1 },
  { category: "Groceries & Food", total_spent: "680.50", transaction_count: 8 },
  { category: "Dining & Coffee", total_spent: "542.80", transaction_count: 14 },
  { category: "Travel & Transport", total_spent: "420.00", transaction_count: 4 },
  { category: "Software & SaaS", total_spent: "184.00", transaction_count: 5 },
  { category: "Health & Fitness", total_spent: "160.00", transaction_count: 2 },
];

export const DUMMY_MONTHLY: MonthlySummary[] = [
  { month: "2025-10", spent: "3920.00", income: "5200.00", net: "1280.00" },
  { month: "2025-11", spent: "4410.00", income: "5200.00", net: "790.00" },
  { month: "2025-12", spent: "4850.00", income: "6500.00", net: "1650.00" },
  { month: "2026-01", spent: "3740.00", income: "5400.00", net: "1660.00" },
  { month: "2026-02", spent: "4210.00", income: "5400.00", net: "1190.00" },
  { month: "2026-03", spent: "3842.10", income: "5500.00", net: "1657.90" },
];

export const DUMMY_TOP_MERCHANTS: MerchantSpend[] = [
  { merchant: "Trader Joe's", total_spent: "480.20", transaction_count: 6 },
  { merchant: "Delta Air Lines", total_spent: "382.40", transaction_count: 1 },
  { merchant: "Equinox Gym", total_spent: "260.00", transaction_count: 1 },
  { merchant: "Apple Store", total_spent: "149.00", transaction_count: 1 },
  { merchant: "Blue Bottle Coffee", total_spent: "84.50", transaction_count: 12 },
  { merchant: "GitHub", total_spent: "21.00", transaction_count: 1 },
];

export const DUMMY_TRANSACTIONS: Transaction[] = [
  {
    id: "tx-1",
    account_id: "acc-1",
    txn_date: "2026-03-02",
    merchant_raw: "POS DEBIT SQ *BLUE BOTTLE COFFEE #104",
    merchant_normalized: "Blue Bottle Coffee",
    description: "Coffee & Pastry",
    amount: "-6.50",
    currency: "USD",
    category_id: 3,
    categorization_source: "RULE",
  },
  {
    id: "tx-2",
    account_id: "acc-2",
    txn_date: "2026-03-01",
    merchant_raw: "TRADER JOE #522 FOLSOM ST SAN FRANCISCO",
    merchant_normalized: "Trader Joe's",
    description: "Weekly Organic Groceries",
    amount: "-74.20",
    currency: "USD",
    category_id: 2,
    categorization_source: "RULE",
  },
  {
    id: "tx-3",
    account_id: "acc-2",
    txn_date: "2026-02-28",
    merchant_raw: "DELTA AIR 0062819201824 ATLANTA GA TKT",
    merchant_normalized: "Delta Air Lines",
    description: "Flight to Austin Conference",
    amount: "-382.40",
    currency: "USD",
    category_id: 4,
    categorization_source: "LLM",
  },
  {
    id: "tx-4",
    account_id: "acc-1",
    txn_date: "2026-02-27",
    merchant_raw: "ACH DIRECT DEPOSIT TECH CORP PAYROLL",
    merchant_normalized: "Tech Corp Payroll",
    description: "Semi-Monthly Salary Deposit",
    amount: "4850.00",
    currency: "USD",
    category_id: 7,
    categorization_source: "RULE",
  },
  {
    id: "tx-5",
    account_id: "acc-3",
    txn_date: "2026-02-26",
    merchant_raw: "APPLE.COM/BILL 866-712-7753 ONE RECURRING",
    merchant_normalized: "Apple Subscription",
    description: "iCloud+ and Apple Music",
    amount: "-14.99",
    currency: "USD",
    category_id: 5,
    categorization_source: "RULE",
  },
  {
    id: "tx-6",
    account_id: "acc-1",
    txn_date: "2026-02-25",
    merchant_raw: "EQUINOX FITNESS SAN FRANCISCO CA DUES",
    merchant_normalized: "Equinox Gym",
    description: "Monthly All-Access Membership",
    amount: "-260.00",
    currency: "USD",
    category_id: 6,
    categorization_source: "RULE",
  },
  {
    id: "tx-7",
    account_id: "acc-3",
    txn_date: "2026-02-24",
    merchant_raw: "GITHUB INC SPONSORS/SUB SAN FRANCISCO CA",
    merchant_normalized: "GitHub",
    description: "GitHub Copilot Subscription",
    amount: "-21.00",
    currency: "USD",
    category_id: 5,
    categorization_source: "RULE",
  },
  {
    id: "tx-8",
    account_id: "acc-2",
    txn_date: "2026-02-22",
    merchant_raw: "UBER TRIP 84920 SAN FRANCISCO HELP.UBER.COM",
    merchant_normalized: "Uber",
    description: "Airport Ride",
    amount: "-37.60",
    currency: "USD",
    category_id: 4,
    categorization_source: "RULE",
  },
];
